blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogsView.as_view(), name='blogs'),
    path('blog_detail/<int:blog_id>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('literature/', include('literature.urls', namespace='literature')),
    path('blogs/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

literature/urls.py
from django.urls import path
from . import views

app_name = 'literature'
urlpatterns = [
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('author_detail/<int:author_id>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('publishers/', views.PublisherView.as_view(), name='publishers'),
    path('publisher_detail/<int:publisher_id>/', views.PublisherDetailView.as_view(), name='publisher_detail'),

    path('translators/', views.TranslatorsView.as_view(), name='translators'),
    path('translator_detail/<int:translator_id>/', views.TranslatorDetailView.as_view(), name='translator_detail'),

    path('books/', views.BooksView.as_view(), name='books'),
    path('book_detail/<int:book_id>/', views.BookDetailView.as_view(), name='book_detail')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:book_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:book_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),

]

orders/models.py
from accounts.models import User
from django.db import models

from literature.models import Book


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['paid', '-updated']

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms


class CartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)


class AddCartForm(forms.Form):
    content_id = forms.IntegerField(widget=
    forms.HiddenInput(attrs={
        'class': 'white-btn mr-10'
    }))

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .forms import CartForm, AddCartForm
from .cart import Cart
from literature.models import Book
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order, OrderItem


class CartView(View):
    template_name = 'orders/cart.html'
    form_class = CartForm

    def get(self, request):
        form = CartForm()
        cart = Cart(request)

        context = {
            'form': form,
            'cart': cart
        }

        return render(request, self.template_name, context)


class CartAddView(View):
    form_class = AddCartForm

    def post(self, request, book_id):
        cart = Cart(request)
        book = get_object_or_404(Book, id=book_id)

        cart.add(book)
        return redirect('literature:book_detail', book.id)


class CartRemoveView(View):
    def get(self, request, book_id):
        cart = Cart(request)
        book = get_object_or_404(Book, id=book_id)
        cart.remove(book)

        return redirect('orders:cart')


class CheckoutView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(
                order=order,
                book=item['book'],
                price=item['price'],
                quantity=item['quantity']
            )
        cart.clear()
        return redirect('orders:order_detail', order.id)


class OrderDetailView(LoginRequiredMixin, View):
    template_name = 'orders/order_detail.html'

    def get(self, request, order_id):
        order = get_object_or_404(Order, id=order_id)
        return render(request, self.template_name, context={'order':order})

orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>

        <div class="breadcrumb-items">
            <div class="row">
                <ul class="breadcrumb">
                    <li>
                        <a href="index.html" class="breadcrumb-link">صفحه اصلی</a>
                    </li>
                    <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                    <li>
                    </li>
                    <li>
                        <a href="categories.html" class="breadcrumb-link">دسته بندی کتب</a>
                    </li>
                    <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                    <li>
                        <span class="breadcrumb-active">سبد خرید</span>
                    </li>
                </ul>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="slider-area">
                        <div class="slider-height2 slider-bg5 d-flex align-items-center justify-content-center">
                            <div class="hero-caption hero-caption2">
                                <h2>سبد خرید</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="cart_area section-padding">
            <div class="container">
                <div class="cart_inner">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">محصول</th>
                                <th scope="col">قیمت</th>
                                <th scope="col">تعداد</th>
                                <th scope="col">جمع نهایی</th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for item in cart %}
                                <tr>
                                    <td>
                                        <div class="media">
                                            <div class="d-flex">
                                                <a href="" target="_self">
                                                    <img src="{{ item.image }}" alt="">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <a href="{% url 'literature:book_detail' item.book.id %}"
                                                   target="_self">کتاب {{ item.title }} اثر
                                                    {{ item.authors }}</a>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <h5>{{ item.price }}<span>تومان</span></h5>
                                    </td>
                                    <td>
                                        <form action="" method="post" novalidate>
                                            <div class="product_count">
                                                <span class="input-number-decrement"> <i class="ti-minus"></i></span>
                                                <input class="input-number" type="text" value="1" min="0" max="10">
                                                <span class="input-number-increment"> <i class="ti-plus"></i></span>
                                            </div>
                                        </form>

                                    </td>
                                    <td>
                                        <h5>{{ item.total_price }}<span>تومان</span></h5>
                                    </td>
                                    <td><a href="{% url 'orders:cart_remove' item.book.id %}"
                                           class="btn">حذف</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            {% if cart|length != 0 %}
                                <tr class="bottom_button">
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <a class="btn" href="#">بروزرسانی سبد خرید</a>
                                    </td>
                                </tr>
                                <tr class="last-tr">
                                    <td>
                                        <h5>پرداخت نهایی</h5>
                                    </td>
                                    <td><h5>390.000<span>تومان</span></h5></td>
                                    <td>

                                    </td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr class="shipping_area">
                                    <td>
                                        <h5>حمل و نقل</h5>
                                    </td>
                                    <td>
                                        <div class="shipping_box">
                                            <ul class="list">
                                                <li>
                                                    ارسال با پست: 70.000 تومان
                                                    <input type="radio"
                                                           aria-label="Radio button for following text input">
                                                </li>
                                                <li>
                                                    ارسال رایگان
                                                    <input type="radio"
                                                           aria-label="Radio button for following text input">
                                                </li>
                                                <li>
                                                    ارسال با پیک: 100.000 تومان
                                                    <input type="radio"
                                                           aria-label="Radio button for following text input">
                                                </li>
                                                <li class="active">
                                                    تحویل حضوری
                                                    <input type="radio"
                                                           aria-label="Radio button for following text input">
                                                </li>
                                            </ul>
                                            <h6>
                                                ماشین حساب حمل و نقل
                                                <i class="fa fa-caret-down" aria-hidden="true"></i>
                                            </h6>
                                            <select class="shipping_select" style="display: none;">
                                                <option value="1">تهران</option>
                                                <option value="2">اصفهان</option>
                                                <option value="3">خوزستان</option>
                                                <option value="4">خراسان رضوی</option>
                                            </select>
                                            <div class="nice-select shipping_select" tabindex="0"><span class="current">تهران</span>
                                                <ul class="list">
                                                    <li data-value="1" class="option selected">تهران</li>
                                                    <li data-value="2" class="option">اصفهان</li>
                                                    <li data-value="3" class="option">خوزستان</li>
                                                    <li data-value="4" class="option">خراسان رضوی</li>
                                                </ul>
                                            </div>
                                            <select class="shipping_select section_bg" style="display: none;">
                                                <option value="1">تهران</option>
                                                <option value="2">دماوند</option>
                                                <option value="3">اسلامشهر</option>
                                                <option value="4">ری</option>
                                            </select>
                                            <div class="nice-select shipping_select section_bg" tabindex="0"><span
                                                    class="current">تهران</span>
                                                <ul class="list">
                                                    <li data-value="1" class="option selected">تهران</li>
                                                    <li data-value="2" class="option">دماوند</li>
                                                    <li data-value="3" class="option">اسلامشهر</li>
                                                    <li data-value="4" class="option">ری</li>
                                                </ul>
                                            </div>
                                            <input class="post_code" type="text" placeholder="کدپستی">
                                            <a class="btn" href="#">بروزرسانی جزئیات</a>
                                        </div>
                                    </td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            {% endif %}

                            </tbody>
                        </table>
                        {% if cart|length != 0 %}
                            <div class="checkout_btn_inner float-right">

                                <a class="btn" href="{% url 'literature:books' %}">ادامه خرید</a>
                                <a class="btn checkout_btn" href="{% url 'orders:checkout'  %}">تسویه حساب</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>

    </main>
{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>

        <div class="breadcrumb-items">
            <div class="row">
                <ul class="breadcrumb">
                    <li>
                        <a href="index.html" class="breadcrumb-link">صفحه اصلی</a>
                    </li>
                    <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                    <li>
                    </li>
                    <li>
                        <a href="categories.html" class="breadcrumb-link">دسته بندی کتب</a>
                    </li>
                    <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                    <li>
                        <a href="cart.html" class="breadcrumb-link">سبد خرید</a>
                    </li>
                    <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                    <li>
                        <span class="breadcrumb-active">تسویه حساب</span>
                    </li>
                </ul>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="slider-area">
                        <div class="slider-height2 slider-bg5 d-flex align-items-center justify-content-center">
                            <div class="hero-caption hero-caption2">
                                <h2>تسویه حساب</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <section class="checkout_area section-padding">
            <div class="container">
                {% if not request.user.is_authenticated %}
                	<div class="returning_customer">
                    <div class="check_title">
                        <h2>
                            قبلاً ثبت نام کرده اید؟
                            <a href="login.html">برای ورود کلیک کنید</a>
                        </h2>
                    </div>
                    <p>
                        اگر قبلاً از ما خرید کرده اید، اطلاعات خود را در بخش پایین وارد کنید و اگر مشتری جدید هستید،
                        لطفاً با تکمیل بخش صورتحساب و حمل و نقل ادامه دهید.
                    </p>
                    <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                        <div class="col-md-6 form-group p_star">
                            <input type="text" class="form-control" id="name" name="name" value=" ">
                            <span class="placeholder" data-placeholder="نام کاربری یا ایمیل"></span>
                        </div>
                        <div class="col-md-6 form-group p_star">
                            <input type="password" class="form-control" id="password" name="password" value="">
                            <span class="placeholder" data-placeholder="رمز عبور"></span>
                        </div>
                        <div class="col-md-12 form-group d-flex flex-wrap">
                            <div class="checkout-cap ml-5">
                                <input type="checkbox" id="fruit01" name="keep-log">
                                <label for="fruit01">ساخت حساب کاربری جدید</label>
                            </div>
                            <a href="login.html" value="submit" class="btn"> ورود</a>

                        </div>
                    </form>
                </div>
                {% endif %}

                <div class="cupon_area">
                    <div class="check_title">
                        <h2> کد تخفیف دارید؟
                            <a href="#">برای وارد کردن کد تخفیف اینجا کلیک کنید</a>
                        </h2>
                    </div>
                    <input type="text" placeholder="کد تخفیف خود را وارد کنید">
                    <a class="btn" href="#">اعمال</a>
                </div>
                <div class="billing_details">
                    <div class="row">
                        <div class="col-lg-8">
                            <h3>جزئیات صورتحساب</h3>
                            <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                                <div class="col-md-6 form-group p_star">
                                    <input type="text" class="form-control" id="first" name="name">
                                    <span class="placeholder" data-placeholder="نام"></span>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <input type="text" class="form-control" id="last" name="name">
                                    <span class="placeholder" data-placeholder="نام خانوادگی"></span>
                                </div>
                                <div class="col-md-12 form-group">
                                    <input type="text" class="form-control" id="company" name="company"
                                           placeholder="شرکت">
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <input type="text" class="form-control" id="number" name="number">
                                    <span class="placeholder" data-placeholder="تلفن همراه"></span>
                                </div>
                                <div class="col-md-6 form-group p_star">
                                    <input type="text" class="form-control" id="email" name="compemailany">
                                    <span class="placeholder" data-placeholder="ایمیل"></span>
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <select class="country_select" style="display: none;">
                                        <option value="1">ایران</option>
                                        <option value="2">سوییس</option>
                                        <option value="4">اسپانیا</option>
                                    </select>
                                    <div class="nice-select country_select" tabindex="0"><span
                                            class="current">ایران</span>
                                        <ul class="list">
                                            <li data-value="1" class="option selected">ایران</li>
                                            <li data-value="2" class="option">سوییس</li>
                                            <li data-value="4" class="option">اسپانیا</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" id="add1" name="add1">
                                    <span class="placeholder" data-placeholder="آدرس خط اول"></span>
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" id="add2" name="add2">
                                    <span class="placeholder" data-placeholder="آدرس خط دوم"></span>
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" id="city" name="city">
                                    <span class="placeholder" data-placeholder="استان"></span>
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <select class="country_select" style="display: none;">
                                        <option value="1">شهر اول</option>
                                        <option value="2">شهر دوم</option>
                                        <option value="4">شهر سوم</option>
                                    </select>
                                    <div class="nice-select country_select" tabindex="0"><span
                                            class="current">شهر اول</span>
                                        <ul class="list">
                                            <li data-value="1" class="option selected">شهر اول</li>
                                            <li data-value="2" class="option">شهر دوم</li>
                                            <li data-value="4" class="option">شهر سوم</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <input type="text" class="form-control" id="zip" name="zip" placeholder="کدپستی">
                                </div>
                                <div class="col-md-12 form-group">
                                    <div class="checkout-cap">
                                        <input type="checkbox" id="fruit1" name="keep-log">
                                        <label for="fruit1">ساخت حساب کاربری؟</label>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <div class="creat_account">
                                        <h3>جزئیات حمل و نقل</h3>
                                        <div class="checkout-cap">
                                            <input type="checkbox" id="f-option3" name="selector">
                                            <label for="f-option3">ارسال به آدرس دیگر؟</label>
                                        </div>
                                    </div>
                                    <textarea class="form-control" name="message" id="message" rows="1"
                                              placeholder="یادداشت سفارش"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="col-lg-4">
                            <div class="order_box">
                                <h2>سفارش شما</h2>
                                <ul class="list">
                                    <li>
                                        <a href="#">محصول<span>جمع</span>
                                        </a>
                                    </li>
                                    {% for item in order.items.all %}
                                    	<li>
                                        <a href="#">
                                            {{ item.book.title }}
                                            <span class="middle">* {{ item.quantity }}</span>
                                            <span class="last">{{ item.get_cost }} تومان</span>
                                        </a>
                                    </li>
                                    {% endfor %}

                                </ul>
                                <ul class="list list_2">
                                    <li>
                                        <a href="#">جمع نهایی <span>{{ order.get_total_price }} تومان</span></a>
                                    </li>
                                    <li>
                                        <a href="#">حمل و نقل
                                            <span>ارسال با پست: 70.000 تومان</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">پرداخت نهایی<span>510.000 تومان</span>
                                        </a>
                                    </li>
                                </ul>
                                <div class="payment_item">
                                    <div class="radion_btn">
                                        <input type="radio" id="f-option5" name="selector">
                                        <label for="f-option5">پرداخت چکی</label>
                                        <div class="check"></div>
                                    </div>
                                    <p> لطفاً چک مورد نظر را به همراه مشخصات کامل و کدپستی به آدرس ما ارسال نمایید. </p>
                                </div>
                                <div class="payment_item active">
                                    <div class="radion_btn">
                                        <input type="radio" id="f-option6" name="selector" checked="">
                                        <label for="f-option6">بانک ملت </label>
                                        <div class="check"></div>
                                    </div>
                                    <p> لطفاً از کارت بانکی خود استفاده کنید. </p>
                                </div>
                                <div class="creat_account checkout-cap">
                                    <input type="checkbox" id="f-option8" name="selector">
                                    <label for="f-option8">تمام <a href="#">شرایط و قوانین*</a> را خواندم و با آن موافق
                                        هستم.
                                    </label>
                                </div>
                                <a class="btn w-100" href="#">پرداخت</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>
{% endblock %}