accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup/message_send_email', views.MessageSendEmailView.as_view(), name='message_send_email'),
    path('signup/finally/<uidb64>/<token>', views.SignUpFinallyView.as_view(), name='signup_finally'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),

    path('profile/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/<int:user_id>/', views.EditProfileView.as_view(), name='edit_profile'),

    path('follow/<int:user_id>/', views.FollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>/', views.UnFollowView.as_view(), name='unfollow'),

    path('post_detail/<int:user_id>/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogsView.as_view(), name='blogs'),
    path('blog_detail/<int:blog_id>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('literature/', include('literature.urls', namespace='literature')),
    path('blogs/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    # path('like/<str:model_name>/<int:object_id>/<str:parent_model_name>/<int:parent_object_id>/', views.LikeCommentView.as_view(), name='like_comment'),
    path('like/<str:model_name>/<int:object_id>/', views.LikeView.as_view(), name='like'),

    path('comment/<int:user_id>/<str:model_name>/<int:object_id>/<str:app_name>/', views.CommentView.as_view(), name='comment'),
    path('comment/<int:user_id>/<str:model_name>/<int:object_id>/<int:comment_id>/<str:app_name>/', views.CommentReplyView.as_view(), name='comment_reply'),

    path('contact_us/', views.ContactUsView.as_view(), name='contact_us'),
    path('about_us/', views.AboutUsView.as_view(), name='about_us'),
]
app_name = 'home'

accounts/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.urls import reverse
from .managers import UserManager
from django.contrib.contenttypes.fields import GenericRelation
from home.models import Like, Comment


class User(AbstractBaseUser):
    email = models.EmailField(unique=True)

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def __str__(self):
        return self.email


class Profile(models.Model):
    GENDER_CHOICES = [
        ('', 'انتخاب جنسیت'),
        ('male', 'مرد'),
        ('female', 'زن'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    phone_number = models.CharField(max_length=11, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(upload_to='profiles/', blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    follower = models.PositiveIntegerField(default=0)
    following = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email} - Profile"


class Relation(models.Model):
    from_user = models.ForeignKey(User, models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, models.CASCADE, related_name='followings')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} following {self.to_user}'


class Post(models.Model):
    user = models.ForeignKey(User, models.CASCADE, related_name='posts')
    title = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120)
    content = models.TextField()
    tags = models.ManyToManyField('home.Tag', related_name='posts', blank=True)
    likes = GenericRelation('home.Like')
    comments = GenericRelation('home.Comment')
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('accounts:post_detail', args=[self.user.id, self.id])

    def get_total_likes(self):
        model_name = self.__class__.__name__.lower()
        number_of_likes = Like.objects.filter(
            content_type=ContentType.objects.get(model=model_name),
            object_id=self.id
        ).count()
        return number_of_likes

    def get_total_comments(self):
        model_name = self.__class__.__name__.lower()
        number_of_comment = Comment.objects.filter(
            content_type=ContentType.objects.get(model=model_name),
            object_id=self.id
        ).count()
        return number_of_comment

    def is_liked(self, request):
        model_name = self.__class__.__name__.lower()
        liked = Like.objects.filter(
            user=request.user,
            content_type=ContentType.objects.get(model=model_name),
            object_id=self.id
        ).exists()
        return liked

accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.contenttypes.models import ContentType
from django.utils.encoding import force_str
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.http import urlsafe_base64_decode
from django.views import View
from .forms import UserCreationForm, UserLoginForm, EditProfileForm, ProfilePostForm
from django.contrib import messages
from utils import email_registration_code
from .tokens import account_activation_token
from .models import User, Relation, Post
from django.contrib.auth.mixins import LoginRequiredMixin
from home.models import Like, Comment
from home.forms import CommentForm, CommentReplyForm, LikeForm

# SignUp
class Signup(View):
    template_name = 'accounts/signup.html'
    form_class = UserCreationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'به صفحه موردنظر دسترسی ندارید.')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        context = {
            'form':form
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = False
            user.save()

            email_registration_code(request, user, form)

            return redirect('accounts:message_send_email')
        return render(request, self.template_name, {'form':form})


class MessageSendEmailView(View):
    template_name = 'accounts/message_send_email.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'به صفحه موردنظر دسترسی ندارید.')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name)


class SignUpFinallyView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'به صفحه موردنظر دسترسی ندارید.')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request, uidb64, token):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'حساب کاربری شم فعال شد')
            return redirect('accounts:login')
        else:
            return render(request, 'accounts/invalid_activation_link.html')


# Login
class Login(View):
    template_name = 'accounts/login.html'
    form_class = UserLoginForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'به صفحه موردنظر دسترسی ندارید.')
            return redirect('home:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        context = {
            'form': form
        }
        return render(request, self.template_name, context=context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            email = cd['email']
            password = cd['password']
            user = authenticate(username=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'خوش آمدید')
                return redirect('home:home')
            else:
                messages.error(request, 'نام کاربری / ایمیل یا رمز عبور اشتباه است.')
                return render(request, self.template_name, {'form': form})
        return render(request, self.template_name, {'form':form})


class LogOut(View):
    def get(self, request):
        logout(request)
        messages.success(request, 'شما از حساب کاربری تان خازج شدید')
        return redirect('home:home')


class ProfileView(View):
    template_name = 'accounts/profile.html'
    form_class = ProfilePostForm

    # def dispatch(self, request, *args, **kwargs):
    #     pass
    #
    def setup(self, request, *args, **kwargs):
        self.user = get_object_or_404(User, pk=kwargs['user_id'])
        super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        is_following = False
        if request.user.is_authenticated:
            relation = Relation.objects.filter(from_user=request.user, to_user=self.user)
            if relation.exists():
                is_following = True

        post_form = self.form_class() if request.user == self.user else None
        posts = Post.objects.filter(user=self.user)

        context = {
            'user': self.user,
            'is_following': is_following,
            'posts': posts,
            'post_form': post_form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        post_form = self.form_class(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, 'پست شما با موفقبت ایجاد شد', 'success')
            return redirect('accounts:profile', user_id=self.user.id)
        return redirect('accounts:profile', user_id=self.user.id)


class EditProfileView(LoginRequiredMixin, View):
    templates_name = 'accounts/edit_profile.html'
    form_class = EditProfileForm

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.user = User.objects.get(pk=kwargs['user_id'])

    def dispatch(self, request, *args, **kwargs):
        if request.user.id != self.user.id:
            return render(request, '404.html', {}, status=404)
        else:
            return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=self.user.id)
        form = self.form_class(instance=request.user.profile)
        context = {'form': form, 'user':user}
        return render(request, self.templates_name, context=context)

    def post(self, request, *args, **kwargs):
        user = User.objects.get(pk=self.user.id)
        form = self.form_class(request.POST, request.FILES, instance=request.user.profile)
        context = {'form': form, 'user':user}
        if form.is_valid():
            form.save()
            messages.success(request, 'پروفایل بروزرسانی شد', 'success')
            return redirect('accounts:profile', user_id=self.user.id)
        return render(request, self.templates_name, context=context)


class FollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(request,'شما کاربر را قبلا دنبال کرده اید.', 'danger')
        else:
            Relation(from_user=request.user, to_user=user).save()
            request.user.profile.following += 1
            request.user.profile.save()
            user.profile.follower += 1
            user.profile.save()
            messages.success(request, 'شما کاربر را از این به بعد دنبال میکنید', 'success')
        return redirect('accounts:profile', user_id)


class UnFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            request.user.profile.following -= 1
            request.user.profile.save()
            user.profile.follower -= 1
            user.profile.save()
            messages.success(request, 'شما کاربر رو دیگر دنبال نمیکنید', 'success')
        else:
            messages.error(request, 'شما کاربر رو دنبال نمیکنید', 'danger')
        return redirect('accounts:profile', user_id)


class PostDetailView(View):
    template_name = 'accounts/post_detail.html'
    form_class = CommentForm
    form_class_reply = CommentReplyForm
    form_class_like = LikeForm
    # form_class_like_comment = LikeCommentForm

    def setup(self, request, *args, **kwargs):
        self.user = User.objects.get(id=kwargs['user_id'])
        self.post = get_object_or_404(Post, user=self.user, id=kwargs['post_id'])
        self.comments = Comment.objects.filter(
            content_type=ContentType.objects.get(model='post', app_label='accounts'),
            object_id=self.post.id,
            is_reply=False
        )
        super().setup(request, *args, **kwargs)

    def get(self, request, user_id, post_id):
        form = self.form_class()
        form_reply = self.form_class_reply()
        form_like = self.form_class_like()
        # form_like_comment = self.form_class_like_comment()

        post = self.post
        liked = post.is_liked(request)
        total_likes = post.get_total_likes()

        return render(request, self.template_name, {
            'post': self.post,
            'model_name': 'post',
            'liked': liked,
            'total_likes': total_likes,
            'comments': self.comments,
            'form': form,
            'form_reply': form_reply,
            'form_like': form_like,
            'app_name': 'accounts'
            # 'form_like_comment': form_like_comment
        })

accounts/templates/accounts/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'accounts:signup_finally' uidb64=uid token=token %}
{% endautoescape %}  

accounts/templates/accounts/edit_profile.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    {% include 'includes/head_links.html' %}
    <title>Document</title>
    <style>
        .avatar {
            vertical-align: middle;
            width: 200px;
            height: 200px;
            border-radius: 50%;
        }
    </style>
</head>

<body>
<main>

    <div class="breadcrumb-items">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="{% url 'home:home' %}" class="breadcrumb-link">صفحه اصلی</a>
                </li>
                <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                <li>
                    <a href="{% url 'accounts:profile' user.id %}" class="breadcrumb-link">پروفایل</a>
                </li>
                <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                <li>
                    <span class="breadcrumb-active">ویرایش پروفایل</span>
                </li>
            </ul>
        </div>
    </div>
    {% include 'includes/messages.html' %}
    <section class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <form class="form-contact contact_form" action="{% url 'accounts:edit_profile' user.id %}" method="post"
                          id="contactForm"
                          novalidate="novalidate" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div style="text-align: center" class="col-lg-12 mb-5">
                            {% if form.instance.profile_picture %}
                                <label for="id_profile_picture">
                                    <img src="{{ form.instance.profile_picture.url }}" alt="Profile Picture"
                                         class="avatar img-thumbnail"
                                         style="cursor: pointer;">
                                </label>
                            {% else %}
                                <label for="id_profile_picture">
                                    <img src="{% static 'img/default_avatar/default-avatar.png' %}" alt="Default Profile Picture"
                                         class="avatar img-thumbnail"
                                         style="cursor: pointer;">
                                </label>
                            {% endif %}
                            <div style="display: none;">
                                {{ form.profile_picture }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    {{ form.phone_number }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ form.date_of_birth }}
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    {{ form.gender }}
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-group">
                                    {{ form.bio }}
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <button type="submit" class="button button-contactForm boxed-btn">ارسال</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
        </div>
    </section>

</main>
{% include 'includes/back-top.html' %}
</body>
</html>

accounts/templates/accounts/profile.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">

<head>
    {% include 'accounts/includes/head_links.html' %}
    <title>قالب html کابانا</title>
    <link rel="stylesheet" href="{% static 'accounts/css/profile_css.css' %}">
    <link rel='stylesheet' href='https://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
</head>

<body>

<main class="register-bg">

    <div class="breadcrumb-items">
        <div class="row">
            <ul class="breadcrumb">
                <li>
                    <a href="{% url 'home:home' %}" class="breadcrumb-link" style="font-size: small">صفحه اصلی</a>
                </li>
                <li class="chevron"><span class="fa fa-chevron-left"></span></li>
                <li>
                    <span class="breadcrumb-active" style="font-size: small">پروفایل</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
        <div class="profile-env">
            <div class="text-center">
                {% include 'includes/messages.html' %}
            </div>
            <header class="row justify-content-center text-center">
                <!-- Profile Picture -->
                <div class="col-lg-12 col-sm-12 mb-3 d-flex justify-content-center" style="width: 40%;">
                    <a href="#" class="profile-picture">
                        {% if user.profile.profile_picture %}
                            <img src="{{ user.profile.profile_picture.url }}"
                                 alt=""
                                 class="img-responsive border-success"
                                 style="border-radius: 50%; width: 120px; height: 120px;">
                        {% else %}
                            <img src="{% static 'img/default_avatar/default-avatar.png' %}" alt=""
                                 class="img-responsive img-circle" style="width: 120px; height: 120px;">
                        {% endif %}
                    </a>
                </div>

                <!-- Profile Info Sections -->
                <div class="col-12 d-flex justify-content-center mt-3">
                    <div class="profile-name">
                        <strong>
                            <a href="#" class="" style="color: #037f81; font-family: monospace">
                                {{ user.profile.first_name }} {{ user.profile.last_name }}
                            </a>
                        </strong>
                    </div>
                </div>

                <hr style="border: none; height: 2px; background-color: #ccc; margin: 20px 0;">
                <div class="col-12 d-flex justify-content-center mb-2">
                    <ul class="profile-info-sections list-unstyled d-flex justify-content-center gap-4">
                        <li>
                            <div class="profile-stat">
                                <h3>{{ user.profile.follower }}</h3>
                                <span>
                        <a href="#">دنبال کنندگان</a>
                    </span>
                            </div>
                        </li>
                        <li>
                            <div class="profile-stat">
                                <h3>{{ user.profile.following }}</h3>
                                <span>
                        <a href="#">دنبال شوندگان</a>
                    </span>
                            </div>
                        </li>
                    </ul>
                </div>

                <!-- Buttons Section -->
                {% if request.user.is_authenticated and request.user.id == user.id %}
                    <div class="row">
                        <div class="col-12 d-flex justify-content-center">
                            <div class="profile-buttons">
                                <div class="form-group mt-3">
                                    <a href="{% url 'accounts:edit_profile' user.id %}"
                                       class="button  button-contactForm boxed-btn"
                                       style="text-decoration: none">
                                        ویرایش پروفایل
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 d-flex justify-content-center">
                            <a href="{% url 'accounts:logout' %}"
                               class="btn-danger boxed-btn"
                               style="text-decoration: none; color: white !important;">
                                خروج از حساب
                            </a>
                        </div>
                    </div>
                {% else %}
                    {% if request.user.is_authenticated %}
                        {% if is_following %}
                            <div class="row">
                                <div class="col-12 d-flex justify-content-center">
                                    <div class="profile-buttons">
                                        <div class="form-group mt-3">
                                            <a href="{% url 'accounts:unfollow' user.id %}"
                                               class="button  button-contactForm boxed-btn btn-danger"
                                               style="text-decoration: none; color: white !important;">
                                                دنبال نکردن
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="col-12 d-flex justify-content-center">
                                    <div class="profile-buttons">
                                        <div class="form-group mt-3">
                                            <a href="{% url 'accounts:follow' user.id %}"
                                               class="button  button-contactForm boxed-btn"
                                               style="text-decoration: none">
                                                دنبال کردن
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <hr style="border: none; height: 2px; background-color: #ccc; margin: 20px 0;">
            </header>
            {% if request.user.is_authenticated and request.user.id == user.id %}
                <div class="row">
                    <div class="col-lg-12">
                        <form class="form-contact" action="{% url 'accounts:profile' user.id %}"
                              method="post"
                              id="contactForm"
                              novalidate="novalidate" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        {{ post_form.title }}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        {{ post_form.content }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group mt-3">
                                <button type="submit" class="button  button-contactForm boxed-btn">پست</button>
                            </div>
                        </form>
                    </div>
                </div>
            {% endif %}

            <section class="profile-feed">
                <!-- profile stories -->
                <div class="profile-stories">
                    <div style="max-width: 100%; margin: auto; background-color: #fff; border: 1px solid #ddd; border-radius: 5px; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); padding: 15px;">
                        {% for post in posts %}
                            <div style="padding: 7px 0;">
                                <div style="font-size: 15px; font-weight: bold; margin-bottom: 5px; color: #000;">
                                    <span>{{ forloop.counter }}</span>.
                                    <a href="{% url 'accounts:post_detail' post.user.id post.id %}"
                                       style="text-decoration: none;
                                       color: #00a4a6;
                                       margin-right: 5px">{{ post.title|truncatewords:'20' }}
                                    </a>
                                </div>
                                <div style="font-size: 12px; color: #888; margin-right: 20px">
                                    <span style="margin-left: 10px;">{{ post.get_total_likes }} لایک</span>
                                    <span>|</span>
                                    <span style="margin-left: 10px;">{{ post.created_at|date:'Y/m/d' }} </span>
                                    <span>|</span>
                                    <span>{{post.get_total_comments}} نظر</span>
                                </div>
                            </div>
                        {% empty %}
                            <p>پستی وجود ندارد!!!</p>
                        {% endfor %}
                    </div>
                    {% if posts %}
                        <div class="text-center" style="margin-top: 5px">
                            <a href="#" class="btn btn-icon icon-left">
                                <i class="entypo-hourglass"></i>
                                بیشتر ...
                            </a>
                        </div>
                    {% endif %}
                </div>
            </section>
        </div>
    </div>


</main>
{% include 'accounts/includes/scripts.html' %}
<script src='https://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>

</body>
</html>