accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.Signup.as_view(), name='signup'),
    path('signup/message_send_email', views.MessageSendEmailView.as_view(), name='message_send_email'),
    path('signup/finally/<uidb64>/<token>', views.SignUpFinallyView.as_view(), name='signup_finally'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),

    path('profile/<int:user_id>/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/<int:user_id>/', views.EditProfileView.as_view(), name='edit_profile'),

    path('follow/<int:user_id>/', views.FollowView.as_view(), name='follow'),
    path('unfollow/<int:user_id>/', views.UnFollowView.as_view(), name='unfollow'),

    path('post_detail/<int:user_id>/<int:post_id>/', views.PostDetailView.as_view(), name='post_detail')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.BlogsView.as_view(), name='blogs'),
    path('blog_detail/<int:blog_id>/<slug:slug>/', views.BlogDetailView.as_view(), name='blog_detail'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('literature/', include('literature.urls', namespace='literature')),
    path('blogs/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    # path('like/<str:model_name>/<int:object_id>/<str:parent_model_name>/<int:parent_object_id>/', views.LikeCommentView.as_view(), name='like_comment'),
    path('like/<str:model_name>/<int:object_id>/', views.LikeView.as_view(), name='like'),

    path('comment/<int:user_id>/<str:model_name>/<int:object_id>/<str:app_name>/', views.CommentView.as_view(), name='comment'),
    path('comment/<int:user_id>/<str:model_name>/<int:object_id>/<int:comment_id>/<str:app_name>/', views.CommentReplyView.as_view(), name='comment_reply'),

    path('contact_us/', views.ContactUsView.as_view(), name='contact_us'),
    path('about_us/', views.AboutUsView.as_view(), name='about_us'),
]
app_name = 'home'

literature/urls.py
from django.urls import path
from . import views

app_name = 'literature'
urlpatterns = [
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('author_detail/<int:author_id>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('publishers/', views.PublisherView.as_view(), name='publishers'),
    path('publisher_detail/<int:publisher_id>/', views.PublisherDetailView.as_view(), name='publisher_detail'),

    path('translators/', views.TranslatorsView.as_view(), name='translators'),
    path('translator_detail/<int:translator_id>/', views.TranslatorDetailView.as_view(), name='translator_detail'),

    path('books/', views.BooksView.as_view(), name='books'),
    path('book_detail/<int:book_id>/', views.BookDetailView.as_view(), name='book_detail')

]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:book_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:book_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),

]

templates/includes/back-top.html
<div id="back-top">
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

templates/includes/footer.html
{% load static %}
{% load book_extras %}
<footer>
    <div class="footer-wrappper section-bg">
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-xl-3 col-lg-5 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">

                                <div class="footer-logo mb-25">
                                    <a href="{% url 'home:home' %}"><img src='{% static "img/logo/logo2_footer.png" %}'
                                                                         alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>با کابانا دسترسی سریع به کتابا</p>
                                    </div>
                                </div>

                                <div class="footer-social">
                                    <a href="https://www.facebook.com/YourPage" target="_blank"><i
                                            class="fab fa-facebook"></i></a>
                                    <a href="https://www.instagram.com/YourProfile" target="_blank"><i
                                            class="fab fa-instagram"></i></a>
                                    <a href="https://www.linkedin.com/in/YourProfile" target="_blank"><i
                                            class="fab fa-linkedin-in"></i></a>
                                    <a href="https://www.youtube.com/c/YourChannel" target="_blank"><i
                                            class="fab fa-youtube"></i></a>
                                    <a href="https://t.me/YourTelegram" target="_blank"><i class="fab fa-telegram"></i></a>

                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>راهنمای سایت</h4>
                                <ul class="mb-20">
                                    <li><a href="{% url 'home:about_us' %}">درباره ما</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-bottom-area">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                کپی رایت &copy; تمام حقوق محفوظ می باشد | توسعه داده شده با <i
                                    class="fa fa-heart color-danger" aria-hidden="true"></i> توسط <a
                                    href="https://www.rtl-theme.com/author/samyar1/products/"
                                    style="color: rgb(0, 0, 0)" target="_blank" rel="nofollow noopener">روحی</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/includes/head_links.html
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href='{% static "img/logo/favicon.png" %}'>

    <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/owl.carousel.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/slicknav.css" %}'>
    <link rel="stylesheet" href='{% static "css/animate.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/magnific-popup.css" %}'>
    <link rel="stylesheet" href='{% static "css/fontawesome-all.min.css" %}'>
    <link rel="stylesheet" href='{% static "css/themify-icons.css" %}'>
    <link rel="stylesheet" href='{% static "css/slick.css" %}'>
    <link rel="stylesheet" href='{% static "css/nice-select.css" %}'>
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
</head>

templates/includes/header.html
{% load static %}
{% load book_extras %}
<header>
    <div class="header-area">
        <div class="main-header ">
            <div class="header-top ">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="d-flex justify-content-between align-items-center flex-sm">
                                <div class="header-info-left d-flex align-items-center">

                                    <div class="logo">
                                        <a href="{% url 'home:home' %}"><img src='{% static "img/logo/logo.png" %}'
                                                                             alt=""></a>
                                    </div>

                                    <form action="{% url 'literature:books' %}" class="form-box" method="get">
                                        <input type="text"
                                               name="search"
                                               placeholder="جستجوی کتاب براساس نویسنده یا انتشارات"
                                               value="{{ request.GET.search }}">
                                        <div class="search-icon">
                                            <button type="submit" style="background: none; border: none;">
                                                <i class="ti-search"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                                <div class="header-info-right d-flex align-items-center">
                                    <ul>
                                        <li><a href="#">راهنما</a></li>
                                        <li><a href="#">پیگیری سفارشات</a></li>
                                        <li class="shopping-card">
                                            <a href="{% url 'orders:cart' %}"><img src='{% static "img/icon/cart.svg" %}' alt=""></a>
                                            {{ cart|length }}
                                        </li>
                                        {% if request.user.is_authenticated %}
                                            <li><a href="{% url 'accounts:profile' request.user.id %}"
                                                   class="btn header-btn">پروفایل</a></li>
                                        {% else %}
                                            <li><a href="{% url 'accounts:login' %}" class="btn header-btn">ورود</a>
                                            </li>
                                        {% endif %}

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-bottom  header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="text-center">
                            {% include 'includes/messages.html' %}
                        </div>
                        <div class="col-xl-12">

                            <div class="logo2">
                                <a href="{% url 'home:home' %}"><img src='{% static "img/logo/logo.png" %}' alt=""></a>
                            </div>

                            <div class="main-menu text-center d-none d-lg-block">
                                <nav>
                                    <ul id="navigation" class="menu">
                                        <li><a href="{% url 'home:home' %}">صفحه اصلی</a></li>

                                        <li><a href="#">دسته بندی موضوعی</a>
                                            <div class="megadrop">
                                                <div class="mega-head">
                                                    {% for group in categories|chunk:3 %}
                                                        <div class="col">
                                                            <ul>
                                                                {% for category in group %}
                                                                    <li>
                                                                        <a href="{% url 'literature:books' %}?category={{ category.id }}">
                                                                            {{ category.name }}
                                                                        </a>
                                                                    </li>
                                                                {% endfor %}
                                                            </ul>
                                                        </div>
                                                    {% endfor %}
                                                </div>
                                                <div class="mega-foot">
                                                    <div class="col-12">
                                                        <a href="{% url 'literature:authors' %}">صفحه نویسندگان</a>
                                                        <a href="{% url 'literature:translators' %}">صفحه مترجمان</a>
                                                        <a href="{% url 'literature:publishers' %}">صفحه ناشران</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li><a href="{% url 'blog:blogs' %}">وبلاگ</a></li>
                                        <li><a href="{% url 'home:about_us' %}">درباره ما</a></li>
                                        <li><a href="{% url 'home:contact_us' %}">تماس با ما</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>

                        <div class="col-xl-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/includes/messages.html
{% if messages %}
<div>
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" style="position: relative; padding: 10px; border: 1px solid #ccc; border-radius: 4px; margin: 5px 0;">
        {{ message }}
        <span class="close-btn" style="position: absolute; top: 5px; right: 10px; cursor: pointer; font-weight: bold;">&times;</span>
    </div>
    {% endfor %}
</div>
<script>
    // پس از بارگذاری کامل صفحه
    document.addEventListener("DOMContentLoaded", function() {
        // پیدا کردن تمامی پیام‌ها
        const alerts = document.querySelectorAll('.alert');

        // حذف خودکار پیام‌ها پس از ۵ ثانیه
        alerts.forEach(function(alert) {
            const closeButton = alert.querySelector('.close-btn');

            // حذف با کلیک روی ضربدر
            closeButton.addEventListener('click', function() {
                alert.style.transition = "opacity 0.5s ease";
                alert.style.opacity = "0";
                setTimeout(() => alert.remove(), 500); // حذف از DOM
            });

            // حذف خودکار
            setTimeout(function() {
                alert.style.transition = "opacity 0.5s ease";
                alert.style.opacity = "0";
                setTimeout(() => alert.remove(), 500); // حذف از DOM
            }, 5000);
        });
    });
</script>
{% endif %}

templates/includes/scripts.html
{% load static %}
<script src='{% static "js/modernizr-3.5.0.min.js" %}'></script>
<script src='{% static "js/jquery-1.12.4.min.js" %}'></script>
<script src='{% static "js/popper.min.js" %}'></script>
<script src='{% static "js/bootstrap.min.js" %}'></script>

<script src='{% static "js/owl.carousel.min.js" %}'></script>
<script src='{% static "js/slick.min.js" %}'></script>
<script src='{% static "js/jquery.slicknav.min.js" %}'></script>

<script src='{% static "js/wow.min.js" %}'></script>
<script src='{% static "js/jquery.magnific-popup.js" %}'></script>
<script src='{% static "js/jquery.nice-select.min.js" %}'></script>
<script src='{% static "js/jquery.counterup.min.js" %}'></script>
<script src='{% static "js/waypoints.min.js" %}'></script>
<script src='{% static "js/nouislider.min.js" %}'></script>

<script src='{% static "js/contact.js" %}'></script>
<script src='{% static "js/jquery.form.js" %}'></script>
<script src='{% static "js/jquery.validate.min.js" %}'></script>
<script src='{% static "js/mail-script.js" %}'></script>
<script src='{% static "js/jquery.ajaxchimp.min.js" %}'></script>
<script src='{% static "js/countdown.js" %}'></script>
<script src='{% static "js/jquery.countdown.min.js" %}'></script>

<script src='{% static "js/plugins.js" %}'></script>
<script src='{% static "js/main.js" %}'></script>



<script>
    $('.countdown_dashboard').countdown({
        diff: null,
        year: 0,
        month: 0,
        day: 50,
        hour: 10,
        min: 10,
        sec: 10,
        refresh: 1000,
        easing: 'linear',
        dash: [{
                key: 'year',
                duration: 950
            },
            {
                key: 'day',
                duration: 950
            },
            {
                key: 'hour',
                duration: 950
            },
            {
                key: 'min',
                duration: 950
            },
            {
                key: 'sec',
                duration: 750
            }
        ],

        onEnd: $.noop
    });
</script>